### ISSUE TITLE
question and issue

### ISSUE THREAD

**Issue by iotEFFIX** [Omniflux/esphome-fujitsu-halcyon#3]
Hello,

i just had a couple of questions. So if i am right i don't have to implement any of the .cpp or .h files into esphome to work because we all get them extern via:
 external_components:
  - source: github://Omniflux/esphome-fujitsu-halcyon
  - source: github://Omniflux/esphome-tzsp
 right?
My issue if this is correct, and i just have to copy and paste the yaml file and change some names where needed.
How to find the file:
packages:
  wifi: !include common/wifi.yaml
 because this file can't be found and is not delivered in this repository i think.

**Comment by Omniflux** [comment]
Correct, external_components now takes care of the .cpp, and .h files.

Packages are explained here https://esphome.io/components/packages.html

If you are not using packages, just replace that section with the wifi or ethernet section from your existing yaml.

You probably also need to change the pins set in the uart section. The example yaml showing tx 13 rx 14 is probably not correct for your device.

If you are using an Atom Lite + FOSV's [Fuji-Atom-Interface](https://github.com/FOSV/Fuji-Atom-Interface) it would be

uart:
  tx_pin: GPIO22
  rx_pin: GPIO19

The circuit in Aaron Zhang's original post I believe uses

uart:
  tx_pin: GPIO17
  rx_pin: GPIO16

**Comment by iotEFFIX** [comment]
Thank you for the answer! Now i have working yaml file that is downloadable. I can also upload it to my esp32 feather and it confirms is has been installed correctly. I just can't get life into it for some reason, no climate template and no acces to the local acces to the site of the esphome project. Do i miss something or is something wrong?
Here is my .yaml file:
```
substitutions:
  name: airco-jd-test
  friendly_name: Airco Jürgen & Davy
  halcyon_name: aircoj&d
  esp_board: featheresp32


external_components:
  - source: github://Omniflux/esphome-fujitsu-halcyon
  - source: github://Omniflux/esphome-tzsp

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: ${esp_board}
  framework:
    type: esp-idf

api:
  password: ""

web_server:
  port: 80

ota:
  platform: esphome
  password: !secret esphome_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Fujitsu"
    password: !secret hotspot_password


sensor:
- platform: uptime
  name: "Uptime"

button:
- platform: restart
  name: Restart device
- platform: safe_mode
  name: Safe Mode Boot

#logger:
#  level: DEBUG

uart:
  tx_pin: GPIO17  # Device dependent
  rx_pin: GPIO16  # Device dependent
  baud_rate: 500
  parity: EVEN

climate:
- platform: fujitsu-halcyon
  name: ${halcyon_name}
  # Fujitsu devices use 0 and 1, but 2-15 should also work. Must not skip addresses
  controller_address: 1  # 0=Primary, 1=Secondary
  #temperature_controller_address: 0  # Fujitsu controller address to read temperature from
  #temperature_sensor_id: my_temp_sensor  # ESPHome sensor to read temperature from
  #ignore_lock: true  # Ignore feature lock

  # To capture communications for debugging / analysis
  # Use Wireshark with https://github.com/Omniflux/fujitsu-airstage-h-dissector
#  tzsp:
#    ip: 192.168.1.20
#    protocol: 255
```
